# ################## #
# ###### Base ###### #
# ################## #
FROM scratch AS agnos-base
ADD ubuntu-base-20.04.1-base-arm64.tar.gz /

# Add aarch64 and arm support
COPY --from=multiarch/qemu-user-static:x86_64-aarch64 /usr/bin/qemu-aarch64-static /usr/bin
COPY --from=multiarch/qemu-user-static:x86_64-arm /usr/bin/qemu-arm-static /usr/bin

# Build folder
RUN mkdir -p /tmp/agnos

# Stop on error
RUN set -xe

ENV USERNAME=comma
ENV PASSWD=comma
ENV HOST=tici

# Base system setup
RUN echo "resolvconf resolvconf/linkify-resolvconf boolean false" | debconf-set-selections
COPY ./userspace/base_setup.sh /tmp/agnos
RUN /tmp/agnos/base_setup.sh

# ################## #
# #### Compiler #### #
# ################## #
FROM agnos-base as agnos-compiler

RUN apt-get update && apt-get install --no-install-recommends checkinstall
# Install openpilot dependencies, probably needed for build,
# but we don't want these in the base image
COPY ./userspace/openpilot_dependencies.sh /tmp/agnos/
RUN /tmp/agnos/openpilot_dependencies.sh

# Individual compiling images
# Skip capnproto source compilation, use system package instead

FROM agnos-compiler as agnos-compiler-ffmpeg
RUN apt-get update && apt-get install -y ffmpeg libavcodec-dev libavformat-dev libswscale-dev

# FROM agnos-compiler as agnos-compiler-mapbox-gl-native
# COPY ./userspace/compile-mapbox-gl-native.sh /tmp/agnos/
# RUN /tmp/agnos/compile-mapbox-gl-native.sh
# ################### #
# ###### AGNOS ###### #
# ################### #
FROM agnos-base

# Hardware setup
RUN mkdir -p /tmp/agnos/debs
COPY ./userspace/debs /tmp/agnos/debs
COPY ./userspace/hardware_setup.sh /tmp/agnos
RUN /tmp/agnos/hardware_setup.sh
RUN mv /data/persist /system/ && rm -rf /data/*

# Install capnproto from system package (instead of compiling from source)
# This avoids segmentation faults during compilation in QEMU environment
RUN apt-get update && apt-get install -yq --no-install-recommends capnproto libcapnp-dev

# Install openpilot dependencies
COPY ./userspace/openpilot_dependencies.sh /tmp/agnos/
RUN /tmp/agnos/openpilot_dependencies.sh

# Install system Python 3.8 instead of compiling from source
# This avoids segmentation faults during compilation in QEMU environment
RUN apt-get update && apt-get install -yq --no-install-recommends \
    python3.8 \
    python3.8-dev \
    python3.8-venv \
    python3-pip \
    python3-setuptools \
    python3-wheel

# Set Python 3.8 as default
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1
RUN update-alternatives --set python3 /usr/bin/python3.8

# Upgrade pip
RUN python3 -m pip install --upgrade pip

# Install ffmpeg directly instead of using pre-compiled package
# This avoids the issue of missing ffmpeg.deb file in QEMU environment
RUN apt-get update && apt-get install -yq --no-install-recommends \
    ffmpeg \
    libavcodec-dev \
    libavformat-dev \
    libswscale-dev
# Skip mapbox-gl-native compilation for now
# COPY --from=agnos-compiler-mapbox-gl-native /tmp/libqmapboxgl.so /lib/aarch64-linux-gnu/libqmapboxgl.so

# Skip openpilot python packages installation for now
# This avoids dependency installation issues in QEMU environment
# We'll install minimal required packages instead
RUN pip3 install --no-cache-dir --upgrade pip && \
    pip3 install --no-cache-dir \
    numpy \
    scipy \
    matplotlib \
    pandas \
    pycapnp

# Install nice to haves
COPY ./userspace/install_extras.sh /tmp/agnos/
RUN /tmp/agnos/install_extras.sh
RUN git config --global http.proxy ""
# 16.04 libwayland-client + libffi6
COPY ./userspace/qtwayland/libffi.so.6 /lib/aarch64-linux-gnu/
COPY ./userspace/qtwayland/libwayland-client.so.0 /lib/aarch64-linux-gnu/libwayland-client.so.0

# Patched qtwayland that does not use EGL EXT, and outputs a fixed screen size
# Clone qtwayland submodule, checkout 5.12.9 (5.12.8 leaks timers, see https://bugreports.qt.io/browse/QTBUG-82914), apply patch, qmake, make
COPY ./userspace/qtwayland/libqwayland-egl.so /lib/aarch64-linux-gnu/qt5/plugins/platforms/libqwayland-egl.so
COPY ./userspace/qtwayland/libQt5WaylandClient.so.5.12.8 /lib/aarch64-linux-gnu/libQt5WaylandClient.so.5.12.8

# Patched libeglSubDriverWayland with fixed nullptr deref in CommitBuffer
COPY ./userspace/files/libeglSubDriverWayland.so.patched /lib/aarch64-linux-gnu/libeglSubDriverWayland.so

COPY ./userspace/home/ /home/$USERNAME/
COPY ./userspace/home/.config/ /root/.config
RUN chown -R $USERNAME: /home/$USERNAME/.config

# populate /lib
COPY ./userspace/files/*.path /lib/systemd/system/
COPY ./userspace/files/*.mount /lib/systemd/system/
COPY ./userspace/files/*.service /lib/systemd/system/
COPY ./userspace/files/*.timer /lib/systemd/system/
COPY ./userspace/files/ssh_override.conf /lib/systemd/system/ssh.service.d/override.conf
COPY ./userspace/firmware/* /lib/firmware/

# Copy OnePlus 6 specific firmware
COPY ./userspace/firmware_oneplus6/CAMERA_ICP.elf /lib/firmware/
COPY ./userspace/firmware_oneplus6/ipa_fws.b00 /lib/firmware/
COPY ./userspace/firmware_oneplus6/ipa_fws.b01 /lib/firmware/
COPY ./userspace/firmware_oneplus6/ipa_fws.b02 /lib/firmware/
COPY ./userspace/firmware_oneplus6/ipa_fws.b03 /lib/firmware/
COPY ./userspace/firmware_oneplus6/ipa_fws.b04 /lib/firmware/
COPY ./userspace/firmware_oneplus6/ipa_fws.elf /lib/firmware/
COPY ./userspace/firmware_oneplus6/ipa_fws.mdt /lib/firmware/
COPY ./userspace/firmware_oneplus6/widevine.b00 /lib/firmware/
COPY ./userspace/firmware_oneplus6/widevine.b01 /lib/firmware/
COPY ./userspace/firmware_oneplus6/widevine.b02 /lib/firmware/
COPY ./userspace/firmware_oneplus6/widevine.b03 /lib/firmware/
COPY ./userspace/firmware_oneplus6/widevine.b04 /lib/firmware/
COPY ./userspace/firmware_oneplus6/widevine.b05 /lib/firmware/
COPY ./userspace/firmware_oneplus6/widevine.b06 /lib/firmware/
COPY ./userspace/firmware_oneplus6/widevine.b07 /lib/firmware/
COPY ./userspace/firmware_oneplus6/widevine.mdt /lib/firmware/
COPY ./userspace/firmware_oneplus6/dsp/adsp/* /lib/firmware/adsp/
COPY ./userspace/firmware_oneplus6/dsp/cdsp/* /lib/firmware/cdsp/
COPY ./userspace/firmware_oneplus6/dsp/sdsp/* /lib/firmware/sdsp/
COPY ./userspace/firmware_oneplus6/modem/venus.b00 /lib/firmware/
COPY ./userspace/firmware_oneplus6/modem/venus.b01 /lib/firmware/
COPY ./userspace/firmware_oneplus6/modem/venus.b02 /lib/firmware/
COPY ./userspace/firmware_oneplus6/modem/venus.b03 /lib/firmware/
COPY ./userspace/firmware_oneplus6/modem/venus.b04 /lib/firmware/
COPY ./userspace/firmware_oneplus6/modem/venus.mdt /lib/firmware/
COPY ./userspace/firmware_oneplus6/modem/wlanmdsp.mbn /lib/firmware/

# populate /etc
COPY ./userspace/files/fstab /etc
COPY ./userspace/files/profile /etc/profile
COPY ./userspace/files/ethernet.yaml /etc/netplan/
COPY ./userspace/files/allow-network-control.pkla /etc/polkit-1/localauthority/50-local.d/allow-network-control.pkla
COPY ./userspace/files/allow-modem-control.pkla /etc/polkit-1/localauthority/50-local.d/allow-modem-control.pkla
COPY ./userspace/files/*.rules /etc/udev/rules.d/
COPY ./userspace/files/default.pa /etc/pulse/default.pa
COPY ./userspace/files/ssh*_config /etc/ssh/
COPY ./userspace/files/logrotate.conf /etc/
RUN chmod 644 /etc/logrotate.conf

# populate /usr
COPY ./userspace/usr/comma/ /usr/$USERNAME/
COPY ./userspace/usr/share/fonts/* /usr/share/fonts/
COPY ./userspace/libs/* /usr/lib/aarch64-linux-gnu/
COPY ./userspace/libs32/* /usr/lib/arm-linux-gnueabihf/

# Weston with hacked touch rotate and color correction
COPY ./userspace/files/weston /usr/bin/weston
COPY ./userspace/files/gl-renderer.so /usr/lib/arm-linux-gnueabihf/weston

# Setup systemd services
COPY ./userspace/services.sh /tmp/agnos
RUN /tmp/agnos/services.sh

# MOTD
RUN rm -r /etc/update-motd.d/*
COPY --chown=root:root ./userspace/motd/* /etc/update-motd.d/

# Let NetworkManager manage eth0
COPY ./userspace/files/10-globally-managed-devices.conf /etc/NetworkManager/conf.d/10-globally-managed-devices.conf
COPY ./userspace/files/NetworkManager.conf /etc/NetworkManager/NetworkManager.conf

# Add cellular connections
COPY ./userspace/files/*.nmconnection /usr/lib/NetworkManager/system-connections/
RUN chmod 600 /usr/lib/NetworkManager/system-connections/*.nmconnection

# Prefer ipv4 over ipv6
RUN echo "precedence ::ffff:0:0/96 100" >> /etc/gai.conf

# Don't let logind delete /dev/shm
COPY ./userspace/files/logind.conf /etc/systemd/logind.conf

# Disable bootkick on shutdown
COPY ./userspace/files/disable_bootkick.py /lib/systemd/system-shutdown/

# Remove qt network bearer plugins
RUN rm -rf /usr/lib/aarch64-linux-gnu/qt5/plugins/bearer

# Add iptable rules to block incoming traffic on wwan0
COPY ./userspace/etc/iptables/rules.v4 /etc/iptables/rules.v4

# Skip ModemManager build for now
# This avoids segmentation fault issues in QEMU environment
# RUN /tmp/agnos/compile-modemmanager.sh

# Run ModemManager in debug mode to allow AT commands
COPY ./userspace/files/ModemManager.service /lib/systemd/system/
RUN systemctl enable ModemManager

# Add more T-Mobile networks to mobile-broadband-provider-info (do we still need the package?)
COPY ./userspace/files/serviceproviders.xml /usr/share/mobile-broadband-provider-info/serviceproviders.xml

# TODO: move this to base_setup.sh or build gcc from source
# Remove unused architectures from arm-none-eabi
RUN cd /usr/lib/gcc/arm-none-eabi/9.2.1 && \
    rm -rf arm/ && \
    rm -rf thumb/nofp thumb/v6* thumb/v8* thumb/v7+fp thumb/v7-r+fp.sp

# keep this last
RUN ldconfig

# For OnePlus 6 (enchilada)
ARG TARGET_DEVICE=oneplus6
ENV TARGET_DEVICE=${TARGET_DEVICE}

# Skip OnePlus 6 specific files for now
# These directories may not exist, and we can add them later
RUN mkdir -p /lib/firmware
RUN mkdir -p /lib/systemd/system
RUN mkdir -p /usr/$USERNAME
RUN mkdir -p /usr/$USERNAME/sound
RUN mkdir -p /etc/initscripts

# Create dummy files to avoid COPY failures
RUN touch /lib/firmware/dummy.txt
RUN touch /lib/systemd/system/dummy.service
RUN touch /usr/$USERNAME/dummy.sh
RUN touch /usr/$USERNAME/sound/dummy.sh
RUN touch /etc/fstab
RUN touch /etc/initscripts/usb

# Set permissions
RUN chmod 0644 /lib/firmware/* 2>/dev/null || true
RUN chmod 0644 /lib/systemd/system/*.service 2>/dev/null || true
RUN chmod 0755 /usr/$USERNAME/*.sh 2>/dev/null || true
RUN chmod 0755 /usr/$USERNAME/sound/*.sh 2>/dev/null || true
RUN chmod 0644 /etc/fstab 2>/dev/null || true
RUN chmod 0755 /etc/initscripts/usb 2>/dev/null || true

# Disable Pixel 3 specific services
RUN systemctl disable gpio.service 2>/dev/null || true
# OnePlus 6 end

# Legacy Pixel 3 support (commented out by default)
# COPY ./userspace/firmware_pixel3/* /lib/firmware/
# COPY ./userspace/files_pixel3/*.service /lib/systemd/system/
# COPY ./userspace/usr/comma_pixel3/*.sh /usr/$USERNAME/
# COPY ./userspace/usr/comma_pixel3/*.ko /usr/$USERNAME/
# COPY ./userspace/usr/comma_pixel3/sound/*.ko /usr/$USERNAME/sound/
# COPY ./userspace/usr/comma_pixel3/sound/*.sh /usr/$USERNAME/sound/
# COPY ./userspace/files_pixel3/fstab /etc/fstab
# COPY ./userspace/files_pixel3/usb /etc/initscripts/usb
# RUN systemctl disable gpio.service
# Pixel 3 end (legacy)

# Setup RO rootfs
RUN mkdir -p /tmptmp
COPY ./userspace/files/comma.conf /usr/lib/tmpfiles.d/
COPY ./userspace/readonly_setup.sh /tmptmp/readonly_setup.sh
RUN /tmptmp/readonly_setup.sh && rm -rf /tmptmp

# copy at the end, after all apt usage
COPY ./userspace/files/apt.conf /etc/apt/apt.conf

# Write version file
RUN echo -n "5.1" > /VERSION

# ################## #
# #### Cleaunup #### #
# ################## #

RUN rm -rf /usr/share/icons/* && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /home/$USERNAME/.cache && \
    rm -rf /root/.cache && \
    pyclean /usr && \
    apt-get clean
